version: '3.8'

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: simple-task-manager
    ports:
      - "3306:3306"