spring:
  datasource:
    url: jdbc:mysql://localhost:3306
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root_password
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true